; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=mips < %s | FileCheck %s -check-prefix=CHECK
; RUN: llc -mtriple=mips --mcpu=zkm < %s | FileCheck %s -check-prefix=CHECK-CPU
; RUN: llc -mtriple=mips --mattr=+inst-same-cost < %s | FileCheck %s -check-prefix=CHECK-CPU

define dso_local noundef range(i32 -5554, 5555) i32 @x(i32 noundef signext %a) local_unnamed_addr #0 {
; CHECK-LABEL: x:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lui $1, 12080
; CHECK-NEXT:    ori $1, $1, 52665
; CHECK-NEXT:    mult $4, $1
; CHECK-NEXT:    mfhi $1
; CHECK-NEXT:    srl $2, $1, 31
; CHECK-NEXT:    sra $1, $1, 10
; CHECK-NEXT:    addu $1, $1, $2
; CHECK-NEXT:    addiu $2, $zero, 5555
; CHECK-NEXT:    mul $1, $1, $2
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    subu $2, $4, $1
;
; CHECK-CPU-LABEL: x:
; CHECK-CPU:       # %bb.0: # %entry
; CHECK-CPU-NEXT:    addiu $1, $zero, 5555
; CHECK-CPU-NEXT:    div $zero, $4, $1
; CHECK-CPU-NEXT:    teq $1, $zero, 7
; CHECK-CPU-NEXT:    jr $ra
; CHECK-CPU-NEXT:    mfhi $2
entry:
  %rem = srem i32 %a, 5555
  ret i32 %rem
}

define dso_local noundef range(i32 -5554, 5555) i32 @y(i32 noundef signext %a) local_unnamed_addr #1 {
; CHECK-LABEL: y:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addiu $1, $zero, 5555
; CHECK-NEXT:    div $zero, $4, $1
; CHECK-NEXT:    teq $1, $zero, 7
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    mfhi $2
;
; CHECK-CPU-LABEL: y:
; CHECK-CPU:       # %bb.0: # %entry
; CHECK-CPU-NEXT:    addiu $1, $zero, 5555
; CHECK-CPU-NEXT:    div $zero, $4, $1
; CHECK-CPU-NEXT:    teq $1, $zero, 7
; CHECK-CPU-NEXT:    jr $ra
; CHECK-CPU-NEXT:    mfhi $2
entry:
  %rem = srem i32 %a, 5555
  ret i32 %rem
}

define dso_local noundef range(i32 -5554, 5555) i32 @z(i32 noundef signext %a) local_unnamed_addr #2 {
; CHECK-LABEL: z:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addiu $1, $zero, 5555
; CHECK-NEXT:    div $zero, $4, $1
; CHECK-NEXT:    teq $1, $zero, 7
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    mfhi $2
;
; CHECK-CPU-LABEL: z:
; CHECK-CPU:       # %bb.0: # %entry
; CHECK-CPU-NEXT:    addiu $1, $zero, 5555
; CHECK-CPU-NEXT:    div $zero, $4, $1
; CHECK-CPU-NEXT:    teq $1, $zero, 7
; CHECK-CPU-NEXT:    jr $ra
; CHECK-CPU-NEXT:    mfhi $2
entry:
  %rem = srem i32 %a, 5555
  ret i32 %rem
}

attributes #0 = { "target-features"="" }
attributes #1 = { "target-features"="+inst-same-cost" }
attributes #2 = { "target-cpu"="zkm" }
